Roles to limit permission by environment
lumoslabs/samson pull request #5
Opened 2019-10-04 01:11 UTC by PolRod

This allows you to have, for example, global deployers or project deployers that can not deploy on production.
Disclaimer: some of the practices here are meant to keep consistency with patterns in the samson codebase, rather than follow lumos' practices  (or my own preferences). Even if we never merge this into zendesk/samson's master, I thought it was better to keep it homogeneous to make potential future developments easier.

2019-10-30 22:52 UTC, farvour commented
My only question is: where are the roles & their environments configured currently? A MySQL database table we already have?

2019-10-30 22:59 UTC, PolRod commented
Currently there is no relationship between roles and environments (this is what the PR does).
However, all this information is indeed stored in the samson_production mysql database.

2020-01-08 21:24 UTC, farvour commented
I recently updated our master from the upstream zendesk project, this may need a rebase?

2023-04-27 16:56 UTC, farvour requested changes
I was noticing this in my approval queue.

May want to just close/remove this. :D

Gracias!

2023-04-27 18:00 UTC, closed without merging